import type { Metadata } from "next";
import "./globals.css";
import VisualEditsMessenger from "../visual-edits/VisualEditsMessenger";
import ErrorReporter from "@/components/ErrorReporter";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>{/* Head is now clean - no inline scripts */}</head>
      <body className="antialiased">
        <ErrorReporter />

        {/* Google Analytics/Ads Scripts */}
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=AW-16972743037"
          strategy="afterInteractive"
        />
        <Script id="google-ads-config" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'AW-16972743037');
          `}
        </Script>

        {/* Conversion Tracking Script - runs after gtag is loaded */}
        <Script id="conversion-tracking" strategy="afterInteractive">
          {`
            gtag('event', 'conversion', {
              'send_to': 'AW-16972743037/1FSJCPPOgpAbEP2Cnp0_'
            });
          `}
        </Script>

        {/* Your existing route messenger script */}
        <Script
          src="https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/scripts//route-messenger.js"
          strategy="afterInteractive"
          data-target-origin="*"
          data-message-type="ROUTE_CHANGE"
          data-include-search-params="true"
          data-only-in-iframe="true"
          data-debug="true"
          data-custom-data='{"appName": "YourApp", "version": "1.0.0", "greeting": "hi"}'
        />

        {children}
        <VisualEditsMessenger />
      </body>
    </html>
  );
}
